// <auto-generated />
using System;
using Honalolo.Information.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Honalolo.Information.Infrastructure.Migrations
{
    [DbContext(typeof(TouristInfoDbContext))]
    [Migration("20260127180454_AddReportsTable")]
    partial class AddReportsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attraction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("ImagesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("images");

                    b.Property<string>("LocationDetails")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CityId");

                    b.HasIndex("TypeId");

                    b.ToTable("Attractions", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.AttractionLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttractionId")
                        .HasColumnType("int")
                        .HasColumnName("attraction_id");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("languages");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.AttractionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attraction_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.ToTable("Attraction_types", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttractionId")
                        .HasColumnType("int")
                        .HasColumnName("attraction_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId")
                        .IsUnique();

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("food_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttractionId")
                        .HasColumnType("int")
                        .HasColumnName("attraction_id");

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("food_type");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId")
                        .IsUnique();

                    b.ToTable("Food", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmenitiesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("amenities");

                    b.Property<int>("AttractionId")
                        .HasColumnType("int")
                        .HasColumnName("attraction_id");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId")
                        .IsUnique();

                    b.ToTable("Hotels", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.OpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttractionId")
                        .HasColumnType("int")
                        .HasColumnName("attraction_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("opening_hours");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.ToTable("Opening_hours", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AltitudeMeters")
                        .HasColumnType("int")
                        .HasColumnName("attlitude_meters");

                    b.Property<int>("AttractionId")
                        .HasColumnType("int")
                        .HasColumnName("attraction_id");

                    b.Property<int?>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevelId")
                        .HasColumnType("int")
                        .HasColumnName("attraction_diffculty_level");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("int")
                        .HasColumnName("distance_meters");

                    b.Property<string>("EndpointPoint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("endpoint_point");

                    b.Property<string>("StartingPoint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("starting_point");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId")
                        .IsUnique();

                    b.ToTable("Trails", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city_name");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Continent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("continent_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("continent_name");

                    b.HasKey("Id");

                    b.ToTable("Continents", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContinentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("region_name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Reports.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("data_json");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("parameters_json");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Attraction", b =>
                {
                    b.HasOne("User", "Author")
                        .WithMany("AuthoredAttractions")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attraction_User");

                    b.HasOne("Honalolo.Information.Domain.Entities.Locations.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Honalolo.Information.Domain.Entities.Attractions.AttractionType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("City");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.AttractionLanguage", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Attractions.Attraction", "Attraction")
                        .WithMany("Languages")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Event", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Attractions.Attraction", "Attraction")
                        .WithOne("EventDetails")
                        .HasForeignKey("Honalolo.Information.Domain.Entities.Attractions.Event", "AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Food", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Attractions.Attraction", "Attraction")
                        .WithOne("FoodDetails")
                        .HasForeignKey("Honalolo.Information.Domain.Entities.Attractions.Food", "AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Hotel", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Attractions.Attraction", "Attraction")
                        .WithOne("HotelDetails")
                        .HasForeignKey("Honalolo.Information.Domain.Entities.Attractions.Hotel", "AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.OpeningHour", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Attractions.Attraction", "Attraction")
                        .WithMany("OpeningHours")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Trail", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Attractions.Attraction", "Attraction")
                        .WithOne("TrailDetails")
                        .HasForeignKey("Honalolo.Information.Domain.Entities.Attractions.Trail", "AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.City", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Locations.Region", "Region")
                        .WithMany("City")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Country", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Locations.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Region", b =>
                {
                    b.HasOne("Honalolo.Information.Domain.Entities.Locations.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Attractions.Attraction", b =>
                {
                    b.Navigation("EventDetails");

                    b.Navigation("FoodDetails");

                    b.Navigation("HotelDetails");

                    b.Navigation("Languages");

                    b.Navigation("OpeningHours");

                    b.Navigation("TrailDetails");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.City", b =>
                {
                    b.Navigation("Attractions");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Continent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Honalolo.Information.Domain.Entities.Locations.Region", b =>
                {
                    b.Navigation("City");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("AuthoredAttractions");
                });
#pragma warning restore 612, 618
        }
    }
}
